### PR TITLE
Minor formatting changes

### PR DESCRIPTION
**Pull request by canyon289**
Hello,
I have interest in this tool and while reviewing the code saw some opportunities to streamline the code base.

The two changes are making the name map a dictionary and moving the declaration of the supported list out of the for loop.

I haven't tested these changes yet, I wanted to run them by you all first to see if you're ok with the idea first!

Hopefully this helps

### CODE REVIEW

**Comment by canyon289** [comment]
I see that some changes were made here that will cause a merge conflict. Since that is the case let me know if you like the general idea, I'd be happy with redoing the changes here once the other PR is merged

https://github.com/x90skysn3k/brutespray/pull/21/files

**Comment by canyon289** [comment]
Great! If you don't mind testing it out to make sure I didn't break anything that would be awesome.

This should all just be style changes with no functionality change.

**Comment by jrobles-r7** [comment]
@x90skysn3k is going to test PR #21 and then we'll take a look at merging this PR.

**Comment by canyon289** [comment]
Thanks!

**Comment by jrobles-r7** [comment]
Thanks for contributing @canyon289  👍

**Pull request merged**
